apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-common
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/labs-home/gitops-core.git
      revision: HEAD
      directories:
      - path: applications/*/envs/common
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/labs-home/gitops-core.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true