apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-core
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: 'https://github.com/labs-home/gitops-core'
      revision: HEAD
      directories:
      - path: applications/*/envs/core
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'
    spec:
      project: core
      source:
        repoURL: 'https://github.com/labs-home/gitops-core'
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true