apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ns.yaml
  - argocd-cm.yaml

helmCharts:
  - name: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 8.1.2
    releaseName: argo-cd
    namespace: argocd
    includeCRDs: true