apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ns.yaml

patchesStrategicMerge:
  - argocd-cm.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.2.0
    namespace: argocd
    includeCRDs: true