apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ns.yaml

helmCharts:
  - name: argocd
    repo: oci://ghcr.io/argoproj/argo-helm
    version: 8.1.2
    releaseName: argocd
    namespace: argocd
    includeCRDs: true
    values:
      configs:
        cm:
          kustomize.buildOptions: "--enable-helm"