apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - ns.yaml
  - repo.yaml
  - root_app.yml

patches:
- target:
    version: v1
    kind: ConfigMap
    name: argocd-cm
  path: argocd-cm.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.2.0
    namespace: argocd
    releaseName: argocd
    includeCRDs: true